name: "Rust: Format Check"

on:
  push:
    branches:
      - main
      - develop
      - testnet
  pull_request:
    branches:
      - main
      - develop
      - testnet

permissions:
  contents: read
  actions: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c 

      - name: Install Rust
        uses: dtolnay/rust-toolchain@1482605baf623a1ba7bb69329c91659433264734
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
