name: "Rust: Format Check"

on:
  push:
    branches:
      - main
      - develop
      - testnet
  pull_request:
    branches:
      - main
      - develop
      - testnet

permissions:
  contents: read
  actions: read

jobs:
  rustfmt:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 
        with:
          persist-credentials: false

      - name: Install Rust
        uses: dtolnay/rust-toolchain@2c7215f132e9ebf062739d9130488b56d53c060c
        with:
          toolchain: stable
          components: rustfmt

      - name: Run rustfmt
        run: cargo fmt -- --check
